---
title: "Bios8060E_Project"
author: "Amanda Blubaugh"
date: 'last updated: 10/8/2019'
output:
  word_document: default
  html_document:
    df_print: paged
---


## Project Overview

### Transcriptomic profile differences in atopic dermatitis (AD) canid house dust mite (HDM) models when considering using multifactorial differential expression for sensitization of model dogs

Plan: Perform differential expression (DE) of previous data from an AD canine model paper in both a multifactoral DE that mimics the original paper (using R open source versus proprietary software of the paper) and in a classic one factor DE without considering an the additional factor of previous canine sensitization to the HDM model. I would like to see how immunological genes that are significantly up or down-regulated change between the two DE evaluations.

## Project Data

Samples from a previously published paper by [Schamber et al. (2014)](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4199687/) will be used for this project


## Sample Source Information

1. N_2847_24h_S
Organism:	Canis lupus familiaris
Source name:	skin_treated_saline_24h
Platform: GPL18789 Series: GSE58442 
FTP download: GEO (TXT) ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM1411nnn/GSM1411196/
Sample		Accession: GSM1411196	ID: 301411196

2. N_2847_24h_A
Organism:	Canis lupus familiaris
Source name:	skin_treated_allergen_24h
Platform: GPL18789 Series: GSE58442 
FTP download: GEO (TXT) ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM1411nnn/GSM1411195/
Sample		Accession: GSM1411195	ID: 301411195

3. N_2845_24h_S
Organism:	Canis lupus familiaris
Source name:	skin_treated_saline_24h
Platform: GPL18789 Series: GSE58442 
FTP download: GEO (TXT) ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM1411nnn/GSM1411191/
Sample		Accession: GSM1411191	ID: 301411191

4. N_2845_24h_A
Organism:	Canis lupus familiaris
Source name:	skin_treated_allergen_24h
Platform: GPL18789 Series: GSE58442 
FTP download: GEO (TXT) ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM1411nnn/GSM1411190/
Sample		Accession: GSM1411190	ID: 301411190

5. N_2845_0h
Organism:	Canis lupus familiaris
Source name:	skin_untreated_0h
Platform: GPL18789 Series: GSE58442 
FTP download: GEO (TXT) ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM1411nnn/GSM1411187/
Sample		Accession: GSM1411187	ID: 301411187

6. N_2802_24h_S
Organism:	Canis lupus familiaris
Source name:	skin_treated_saline_24h
Platform: GPL18789 Series: GSE58442 
FTP download: GEO (TXT) ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM1411nnn/GSM1411186/
Sample		Accession: GSM1411186	ID: 301411186

7. N_2802_24h_A
Organism:	Canis lupus familiaris
Source name:	skin_treated_allergen_24h
Platform: GPL18789 Series: GSE58442 
FTP download: GEO (TXT) ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM1411nnn/GSM1411185/
Sample		Accession: GSM1411185	ID: 301411185

8. N_2802_0h
Organism:	Canis lupus familiaris
Source name:	skin_untreated_0h
Platform: GPL18789 Series: GSE58442 
FTP download: GEO (TXT) ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM1411nnn/GSM1411182/
Sample		Accession: GSM1411182	ID: 301411182

9. N_2800_24h_S
Organism:	Canis lupus familiaris
Source name:	skin_treated_saline_24h
Platform: GPL18789 Series: GSE58442 
FTP download: GEO (TXT) ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM1411nnn/GSM1411181/
Sample		Accession: GSM1411181	ID: 301411181

10. N_2800_24h_A
Organism:	Canis lupus familiaris
Source name:	skin_treated_allergen_24h
Platform: GPL18789 Series: GSE58442 
FTP download: GEO (TXT) ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM1411nnn/GSM1411180/
Sample		Accession: GSM1411180	ID: 301411180

11. N_2847_0h
Organism:	Canis lupus familiaris
Source name:	skin_untreated_0h
Platform: GPL18789 Series: GSE58442 
FTP download: GEO (TXT) ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM1411nnn/GSM1411192/
Sample		Accession: GSM1411192	ID: 301411192

12. N_2800_0h
Organism:	Canis lupus familiaris
Source name:	skin_untreated_0h
Platform: GPL18789 Series: GSE58442 
FTP download: GEO (TXT) ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM1411nnn/GSM1411177/
Sample		Accession: GSM1411177	ID: 301411177

13. N_2716_24h_S
Organism:	Canis lupus familiaris
Source name:	skin_treated_saline_24h
Platform: GPL18789 Series: GSE58442 
FTP download: GEO (TXT) ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM1411nnn/GSM1411176/
Sample		Accession: GSM1411176	ID: 301411176

14. N_2716_24h_A
Organism:	Canis lupus familiaris
Source name:	skin_treated_allergen_24h
Platform: GPL18789 Series: GSE58442 
FTP download: GEO (TXT) ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM1411nnn/GSM1411175/
Sample		Accession: GSM1411175	ID: 301411175

15. N_2716_0h
Organism:	Canis lupus familiaris
Source name:	skin_untreated_0h
Platform: GPL18789 Series: GSE58442 
FTP download: GEO (TXT) ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM1411nnn/GSM1411172/
Sample		Accession: GSM1411172	ID: 301411172

16. N_2704_24h_S
Organism:	Canis lupus familiaris
Source name:	skin_treated_saline_24h
Platform: GPL18789 Series: GSE58442 
FTP download: GEO (TXT) ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM1411nnn/GSM1411171/
Sample		Accession: GSM1411171	ID: 301411171

17. N_2704_24h_A
Organism:	Canis lupus familiaris
Source name:	skin_treated_allergen_24h
Platform: GPL18789 Series: GSE58442 
FTP download: GEO (TXT) ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM1411nnn/GSM1411170/
Sample		Accession: GSM1411170	ID: 301411170

18. N_2704_0h
Organism:	Canis lupus familiaris
Source name:	skin_untreated_0h
Platform: GPL18789 Series: GSE58442 
FTP download: GEO (TXT) ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM1411nnn/GSM1411167/
Sample		Accession: GSM1411167	ID: 301411167

19. A_2855_24h_S
Organism:	Canis lupus familiaris
Source name:	skin_treated_saline_24h
Platform: GPL18789 Series: GSE58442 
FTP download: GEO (TXT) ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM1411nnn/GSM1411166/
Sample		Accession: GSM1411166	ID: 301411166

20. A_2855_24h_A
Organism:	Canis lupus familiaris
Source name:	skin_treated_allergen_24h
Platform: GPL18789 Series: GSE58442 
FTP download: GEO (TXT) ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM1411nnn/GSM1411165/
Sample		Accession: GSM1411165	ID: 301411165

21. A_2855_0h
Organism:	Canis lupus familiaris
Source name:	skin_untreated_0h
Platform: GPL18789 Series: GSE58442 
FTP download: GEO (TXT) ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM1411nnn/GSM1411162/
Sample		Accession: GSM1411162	ID: 301411162

22. A_2853_24h_S
Organism:	Canis lupus familiaris
Source name:	skin_treated_saline_24h
Platform: GPL18789 Series: GSE58442 
FTP download: GEO (TXT) ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM1411nnn/GSM1411161/
Sample		Accession: GSM1411161	ID: 301411161

23. A_2853_24h_A
Organism:	Canis lupus familiaris
Source name:	skin_treated_allergen_24h
Platform: GPL18789 Series: GSE58442 
FTP download: GEO (TXT) ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM1411nnn/GSM1411160/
Sample		Accession: GSM1411160	ID: 301411160

24. A_2853_0h
Organism:	Canis lupus familiaris
Source name:	skin_untreated_0h
Platform: GPL18789 Series: GSE58442 
FTP download: GEO (TXT) ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM1411nnn/GSM1411157/
Sample		Accession: GSM1411157	ID: 301411157

25. A_2841_24h_S
Organism:	Canis lupus familiaris
Source name:	skin_treated_saline_24h
Platform: GPL18789 Series: GSE58442 
FTP download: GEO (TXT) ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM1411nnn/GSM1411156/
Sample		Accession: GSM1411156	ID: 301411156

26. A_2841_24h_A
Organism:	Canis lupus familiaris
Source name:	skin_treated_allergen_24h
Platform: GPL18789 Series: GSE58442 
FTP download: GEO (TXT) ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM1411nnn/GSM1411155/
Sample		Accession: GSM1411155	ID: 301411155

27. A_2841_0h
Organism:	Canis lupus familiaris
Source name:	skin_untreated_0h
Platform: GPL18789 Series: GSE58442 
FTP download: GEO (TXT) ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM1411nnn/GSM1411152/
Sample		Accession: GSM1411152	ID: 301411152

28. A_2840_24h_S
Organism:	Canis lupus familiaris
Source name:	skin_treated_saline_24h
Platform: GPL18789 Series: GSE58442 
FTP download: GEO (TXT) ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM1411nnn/GSM1411151/
Sample		Accession: GSM1411151	ID: 301411151

29. A_2840_24h_A
Organism:	Canis lupus familiaris
Source name:	skin_treated_allergen_24h
Platform: GPL18789 Series: GSE58442 
FTP download: GEO (TXT) ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM1411nnn/GSM1411150/
Sample		Accession: GSM1411150	ID: 301411150

30. A_2840_0h
Organism:	Canis lupus familiaris
Source name:	skin_untreated_0h
Platform: GPL18789 Series: GSE58442 
FTP download: GEO (TXT) ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM1411nnn/GSM1411147/
Sample		Accession: GSM1411147	ID: 301411147

31. A_2839_24h_S
Organism:	Canis lupus familiaris
Source name:	skin_treated_saline_24h
Platform: GPL18789 Series: GSE58442 
FTP download: GEO (TXT) ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM1411nnn/GSM1411146/
Sample		Accession: GSM1411146	ID: 301411146

32. A_2839_24h_A
Organism:	Canis lupus familiaris
Source name:	skin_treated_allergen_24h
Platform: GPL18789 Series: GSE58442 
FTP download: GEO (TXT) ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM1411nnn/GSM1411145/
Sample		Accession: GSM1411145	ID: 301411145

33. A_2839_0h
Organism:	Canis lupus familiaris
Source name:	skin_untreated_0h
Platform: GPL18789 Series: GSE58442 
FTP download: GEO (TXT) ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM1411nnn/GSM1411142/
Sample		Accession: GSM1411142	ID: 301411142

34. A_2838_24h_S
Organism:	Canis lupus familiaris
Source name:	skin_treated_saline_24h
Platform: GPL18789 Series: GSE58442 
FTP download: GEO (TXT) ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM1411nnn/GSM1411141/
Sample		Accession: GSM1411141	ID: 301411141

35. A_2838_24h_A
Organism:	Canis lupus familiaris
Source name:	skin_treated_allergen_24h
Platform: GPL18789 Series: GSE58442 
FTP download: GEO (TXT) ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM1411nnn/GSM1411140/
Sample		Accession: GSM1411140	ID: 301411140

36. A_2838_0h
Organism:	Canis lupus familiaris
Source name:	skin_untreated_0h
Platform: GPL18789 Series: GSE58442 
FTP download: GEO (TXT) ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM1411nnn/GSM1411137/
Sample		Accession: GSM1411137	ID: 301411137
